### ISSUE TITLE
replace either project.id in credentials or readme

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/readepi#12]
This code didn't worked, bu after looking at the `show_example_file()` object, I make it run by replacing the `project.id` from `TEST_REDCap` to `SD_DATA`

Here is the error as written in the README

``` r
library(readepi)
show_example_file()
#>	user_name                     	password
#> 1: 	admin                     	district
#> 2:	rfamro                            	 
#> 3: 	kmane 9A81268476645C4E5F03428B8AC3AA7B
#>                         	host_name project_id
#> 1:    	https://play.dhis2.org/dev/ DHIS2_DEMO
#> 2:    	mysql-rfam-public.ebi.ac.uk   	Rfam
#> 3: https://bbmc.ouhsc.edu/redcap/api/	SD_DATA
#>                         	comment   dbms port
#> 1:  	this is a test DHIS2 server  DHIS2   NA
#> 2:  	this is a test MySQL server  MySQL 4497
#> 3: testing access to REDCap project REDCap   NA
credentials.file <- system.file("extdata", "test.ini", package = "readepi")
dat <- readepi(
  credentials.file = credentials.file,
  project.id = "TEST_REDCap"
)
#> Error in read_credentials(credentials.file, project.id): Credential details for TEST_REDCap not found in credential file.
dat
#> Error in eval(expr, envir, enclos): object 'dat' not found
```

<sup>Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Here is the same code with the replacement

``` r
library(readepi)
show_example_file()
#>	user_name                     	password
#> 1: 	admin                     	district
#> 2:	rfamro                            	 
#> 3: 	kmane 9A81268476645C4E5F03428B8AC3AA7B
#>                         	host_name project_id
#> 1:    	https://play.dhis2.org/dev/ DHIS2_DEMO
#> 2:    	mysql-rfam-public.ebi.ac.uk   	Rfam
#> 3: https://bbmc.ouhsc.edu/redcap/api/	SD_DATA
#>                         	comment   dbms port
#> 1:  	this is a test DHIS2 server  DHIS2   NA
#> 2:  	this is a test MySQL server  MySQL 4497
#> 3: testing access to REDCap project REDCap   NA
credentials.file <- system.file("extdata", "test.ini", package = "readepi")
readepi(
  credentials.file = credentials.file,
  project.id = "SD_DATA"
)
#> Starting to read 5 records  at 2023-04-21 19:09:11.
#>
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_double(),
#>   name_first = col_character(),
#>   name_last = col_character(),
#>   address = col_character(),
#>   telephone = col_character(),
#>   email = col_character(),
#>   dob = col_date(format = ""),
#>   comments = col_character(),
#>   mugshot = col_character()
#> )
#> ℹ Use `spec()` for the full column specifications.
#> $data
#>   record_id name_first name_last                             	address
#> 1     	1 	Nutmeg  Nutmouse 14 Rose Cottage St.\nKenning UK, 323232
#> 2     	2 	Tumtum  Nutmouse 14 Rose Cottage Blvd.\nKenning UK 34243
#> 3     	3 	Marcus  	Wood      	243 Hill St.\nGuthrie OK 73402
#> 4     	4  	Trudy   	DAG      	342 Elm\nDuncanville TX, 75116
#> 5     	5   John Lee	Walker  	Hotel Suite\nNew Orleans LA, 70115
#>    	telephone           	email    	dob age sex demographics_complete
#> 1 (405) 321-1111 	nutty@mouse.com 2003-08-30  11   0                 	2
#> 2 (405) 321-2222	tummy@mouse.comm 2003-03-10  11   1                 	2
#> 3 (405) 321-3333    	mw@mwood.net 1934-04-09  80   1                 	2
#> 4 (405) 321-4444 peroxide@blonde.com 1952-11-02  61   0                 	2
#> 5 (405) 321-5555  left@hippocket.com 1955-04-15  59   1                 	2
#>   height weight   bmi
#> 1   7.00  	1 204.1
#> 2   6.00  	1 277.8
#> 3 180.00 	80  24.7
#> 4 165.00 	54  19.8
#> 5 193.04	104  27.9
#>                                                                                                  	comments
#> 1                                                                 	Character in a book, with some guessing
#> 2                                                                      	A mouse character from a good book
#> 3                                                                                      	completely made up
#> 4 This record doesn't have a DAG assigned\n\nSo call up Trudy on the telephone\nSend her a letter in the mail
#> 5             	Had a hand for trouble and a eye for cash\n\nHe had a gold watch chain and a black mustache
#>     	mugshot health_complete race___1 race___2 race___3 race___4 race___5
#> 1 mugshot-1.jpg           	1    	0    	0    	0    	0    	1
#> 2 mugshot-2.jpg           	0    	0    	0    	1    	0    	1
#> 3 mugshot-3.jpg           	2    	0    	0    	0    	1    	1
#> 4 mugshot-4.jpg           	2    	0    	1    	0    	0    	1
#> 5 mugshot-5.jpg           	0    	1    	0    	0    	0    	0
#>   race___6 ethnicity interpreter_needed race_and_ethnicity_complete
#> 1    	0     	1              	0                       	2
#> 2    	0     	1              	0                       	0
#> 3    	0     	0              	1                       	2
#> 4    	0     	1             	NA                       	2
#> 5    	1     	2              	0                       	2
#>
#> $metadata
#> # A tibble: 17 × 18
#>	field_name     	form_name      	section_header   field_type field_label
#>	<chr>          	<chr>          	<chr>        	<chr>  	<chr> 	 
#>  1 record_id      	demographics   	<NA>         	text   	Study ID   
#>  2 name_first     	demographics   	Contact Informa… text   	First Name
#>  3 name_last      	demographics   	<NA>         	text   	Last Name  
#>  4 address        	demographics   	<NA>         	notes  	Street, Ci…
#>  5 telephone      	demographics   	<NA>         	text   	Phone numb…
#>  6 email          	demographics   	<NA>         	text   	E-mail	 
#>  7 dob            	demographics   	<NA>         	text   	Date of bi…
#>  8 age            	demographics   	<NA>         	text   	Age (years)
#>  9 sex            	demographics   	<NA>         	radio  	Gender	 
#> 10 height         	health         	<NA>         	text   	Height (cm)
#> 11 weight         	health         	<NA>         	text   	Weight (ki…
#> 12 bmi            	health         	<NA>         	calc   	BMI   	 
#> 13 comments       	health         	General Comments notes  	Comments   
#> 14 mugshot        	health         	<NA>         	file   	Mugshot    
#> 15 race           	race_and_ethnicity <NA>         	checkbox   Race (Sele…
#> 16 ethnicity      	race_and_ethnicity <NA>         	radio  	Ethnicity  
#> 17 interpreter_needed race_and_ethnicity <NA>         	truefalse  Are interp…
#> # ℹ 13 more variables: select_choices_or_calculations <chr>, field_note <chr>,
#> #   text_validation_type_or_show_slider_number <chr>,
#> #   text_validation_min <chr>, text_validation_max <chr>, identifier <chr>,
#> #   branching_logic <chr>, required_field <chr>, custom_alignment <chr>,
#> #   question_number <chr>, matrix_group_name <chr>, matrix_ranking <chr>,
#> #   field_annotation <chr>
```

<sup>Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Karim-Mane** [comment]
I saw this when I was making the recent updates. I have it fixed now.

**Comment by avallecam** [comment]
I reinstalled the `develop` branch and still having this issue

From this 

https://github.com/epiverse-trace/readepi/blob/ea6c8037b4d641ad3388ef8dc26fbbdf9a828756/README.Rmd#L97-L101

I get this:

``` r
# READING ALL FIELDS AND RECORDS FROM A REDCap PROJECT
readepi(
  credentials_file = credentials_file,
  project_id = "TEST_REDCap"
)
#> Error in read_credentials(credentials_file, project_id): Credential details for TEST_REDCap not found in
#>          credential file.
```

I reviewed that the REDCap dbms still have the "SD_DATA" in the [`test.ini` file](https://github.com/epiverse-trace/readepi/blob/develop/inst/extdata/test.ini), which could be the source of the issue

https://github.com/epiverse-trace/readepi/blob/ea6c8037b4d641ad3388ef8dc26fbbdf9a828756/inst/extdata/test.ini#L1-L4

Here is a full reprex

``` r
library(readepi)

# DISPLAY THE STRUCTURE OF THE CREDENTIALS FILE
show_example_file()
#>    user_name                         password
#> 1:     admin                         district
#> 2:    rfamro                                 
#> 3:     kmane 9A81268476645C4E5F03428B8AC3AA7B
#>                             host_name project_id
#> 1:        https://play.dhis2.org/dev/ DHIS2_DEMO
#> 2:        mysql-rfam-public.ebi.ac.uk       Rfam
#> 3: https://bbmc.ouhsc.edu/redcap/api/    SD_DATA
#>                             comment   dbms port
#> 1:      this is a test DHIS2 server  DHIS2   NA
#> 2:      this is a test MySQL server  MySQL 4497
#> 3: testing access to REDCap project REDCap   NA

# DEFINING THE CREDENTIALS FILE
credentials_file <- system.file("extdata", "test.ini", package = "readepi")

# READING ALL FIELDS AND RECORDS FROM A REDCap PROJECT
readepi(
  credentials_file = credentials_file,
  project_id = "TEST_REDCap"
)
#> Error in read_credentials(credentials_file, project_id): Credential details for TEST_REDCap not found in
#>          credential file.

readepi(
  credentials_file = credentials_file,
  project_id = "SD_DATA"
)
#> Starting to read 5 records  at 2023-05-05 19:06:17.
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_double(),
#>   name_first = col_character(),
#>   name_last = col_character(),
#>   address = col_character(),
#>   telephone = col_character(),
#>   email = col_character(),
#>   dob = col_date(format = ""),
#>   comments = col_character(),
#>   mugshot = col_character()
#> )
#> ℹ Use `spec()` for the full column specifications.
#> $data
#>   record_id name_first name_last                                 address
#> 1         1     Nutmeg  Nutmouse 14 Rose Cottage St.\nKenning UK, 323232
#> 2         2     Tumtum  Nutmouse 14 Rose Cottage Blvd.\nKenning UK 34243
#> 3         3     Marcus      Wood          243 Hill St.\nGuthrie OK 73402
#> 4         4      Trudy       DAG          342 Elm\nDuncanville TX, 75116
#> 5         5   John Lee    Walker      Hotel Suite\nNew Orleans LA, 70115
#>        telephone               email        dob age sex demographics_complete
#> 1 (405) 321-1111     nutty@mouse.com 2003-08-30  11   0                     2
#> 2 (405) 321-2222    tummy@mouse.comm 2003-03-10  11   1                     2
#> 3 (405) 321-3333        mw@mwood.net 1934-04-09  80   1                     2
#> 4 (405) 321-4444 peroxide@blonde.com 1952-11-02  61   0                     2
#> 5 (405) 321-5555  left@hippocket.com 1955-04-15  59   1                     2
#>   height weight   bmi
#> 1   7.00      1 204.1
#> 2   6.00      1 277.8
#> 3 180.00     80  24.7
#> 4 165.00     54  19.8
#> 5 193.04    104  27.9
#>                                                                                                      comments
#> 1                                                                     Character in a book, with some guessing
#> 2                                                                          A mouse character from a good book
#> 3                                                                                          completely made up
#> 4 This record doesn't have a DAG assigned\n\nSo call up Trudy on the telephone\nSend her a letter in the mail
#> 5                 Had a hand for trouble and a eye for cash\n\nHe had a gold watch chain and a black mustache
#>         mugshot health_complete race___1 race___2 race___3 race___4 race___5
#> 1 mugshot-1.jpg               1        0        0        0        0        1
#> 2 mugshot-2.jpg               0        0        0        1        0        1
#> 3 mugshot-3.jpg               2        0        0        0        1        1
#> 4 mugshot-4.jpg               2        0        1        0        0        1
#> 5 mugshot-5.jpg               0        1        0        0        0        0
#>   race___6 ethnicity interpreter_needed race_and_ethnicity_complete
#> 1        0         1                  0                           2
#> 2        0         1                  0                           0
#> 3        0         0                  1                           2
#> 4        0         1                 NA                           2
#> 5        1         2                  0                           2
#> 
#> $metadata
#> # A tibble: 17 × 18
#>    field_name         form_name          section_header   field_type field_label
#>    <chr>              <chr>              <chr>            <chr>      <chr>      
#>  1 record_id          demographics       <NA>             text       Study ID   
#>  2 name_first         demographics       Contact Informa… text       First Name 
#>  3 name_last          demographics       <NA>             text       Last Name  
#>  4 address            demographics       <NA>             notes      Street, Ci…
#>  5 telephone          demographics       <NA>             text       Phone numb…
#>  6 email              demographics       <NA>             text       E-mail     
#>  7 dob                demographics       <NA>             text       Date of bi…
#>  8 age                demographics       <NA>             text       Age (years)
#>  9 sex                demographics       <NA>             radio      Gender     
#> 10 height             health             <NA>             text       Height (cm)
#> 11 weight             health             <NA>             text       Weight (ki…
#> 12 bmi                health             <NA>             calc       BMI        
#> 13 comments           health             General Comments notes      Comments   
#> 14 mugshot            health             <NA>             file       Mugshot    
#> 15 race               race_and_ethnicity <NA>             checkbox   Race (Sele…
#> 16 ethnicity          race_and_ethnicity <NA>             radio      Ethnicity  
#> 17 interpreter_needed race_and_ethnicity <NA>             truefalse  Are interp…
#> # ℹ 13 more variables: select_choices_or_calculations <chr>, field_note <chr>,
#> #   text_validation_type_or_show_slider_number <chr>,
#> #   text_validation_min <chr>, text_validation_max <chr>, identifier <chr>,
#> #   branching_logic <chr>, required_field <chr>, custom_alignment <chr>,
#> #   question_number <chr>, matrix_group_name <chr>, matrix_ranking <chr>,
#> #   field_annotation <chr>
```

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Karim-Mane** [comment]
I just realised that I did not make the update the redcap project name in the README.md

I only did it in the vignette.

Corrected it now - thanks

**Comment by avallecam** [comment]
You're right, in the vignette is correct, and everything will be standardized to `"SD_DATA"`

https://github.com/epiverse-trace/readepi/blob/0035a9adc03745b78988efa673d76b7e7cb33e49/README.Rmd#L100

**Comment by avallecam** [comment]
thanks! https://github.com/epiverse-trace/readepi/commit/f83c6c178b5d0ebd4cf3e303fe0627f39aafeb28
